### ISSUE TITLE
Too easy to decode

### ISSUE THREAD

**Issue by ghost** [TheCountVevo/OxyCo#1]
I Know, it's designed and coded to be easy, but, why not encrypt with a random key (random lenght too) shared only for the user and the two programs (encode and decode) ? and then create a program that translate the key into the dict

Je sais, ça a été désignée et codé pour être facile, mais, pourquoi ne pas encrypter avec une key aléatoire (de longeur aléatoire) partagé seulement entre l'user et les deux programmes (encode and decode) ? puis avoir un programme qui traduit la clé en un dictionnaire

**Comment by vev0s** [comment]
I will try to resolve this, but it's a little bit hard to do ! This commit will be soon !

**Comment by ghost** [comment]
Okay, i think i can wait
